# docker-compose.yml

# docker compose schema version no longer required

services:
  # The main application service
  orchestrator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sentinel_orchestrator
    # The .env_file directive loads variables from the .env file for local development.
    env_file:
      - .env
    ports:
      - "8000:8000"
    # Mount the local source code into the container for hot-reloading.
    # This is for development only. In production, the code is baked into the image.
    volumes:
      - ./api:/app/api
      - ./core:/app/core
      - ./main.py:/app/main.py
    # Use depends_on to control startup order. The orchestrator will not start
    # until redis and weaviate report that they are healthy.
    depends_on:
      redis:
        condition: service_healthy
      weaviate:
        condition: service_healthy
    networks:
      - sentinel-net

  # L1 Cache: Redis
  redis:
    image: redis/redis-stack:latest
    container_name: sentinel_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    # Healthcheck ensures the orchestrator waits until Redis is ready.
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - sentinel-net

  # L2 Memory: Weaviate
  weaviate:
    image: semitechnologies/weaviate:1.24.1
    container_name: sentinel_weaviate
    ports:
      - "8080:8080"
    restart: on-failure:0
    volumes:
      - weaviate_data:/var/lib/weaviate
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      CLUSTER_HOSTNAME: 'node1'
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/v1/.well-known/ready"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - sentinel-net

# Define named volumes to persist data across container restarts.
volumes:
  redis_data:
    driver: local
  weaviate_data:
    driver: local

# Define a custom bridge network for our services to communicate.
networks:
  sentinel-net:
    driver: bridge