name: Grafana Dashboard Lint

on:
  push:
    paths:
      - 'docs/dashboards/*.json'
      - '.github/workflows/grafana-lint.yml'

jobs:
  lint-grafana-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate JSON dashboards
        run: |
          for f in docs/dashboards/*.json; do
            echo "Validating $f..."
            python3 -m json.tool "$f" > /dev/null || exit 1
          done
