name: Helm Chart Lint & Package

on:
  push:
    branches: [main]

jobs:
  helm-lint-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.13.3
      - name: Lint Helm chart
        run: helm lint helm
      - name: Package Helm chart
        run: helm package helm --destination packaged-helm

