name: Ingest Smoke Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ingest-smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install
      - name: Run ingestion smoke test
        run: pytest tests/test_ingest.py::test_ingest_and_search -q
