name: Release

on:
  push:
    tags:
      - 'v*.*.*'
  pull_request:

jobs:
  lint-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v6
        with:
          types: feat, fix, chore, docs, refactor, style, test, perf

  changelog-enforcement:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Extract version
        id: get_version
        run: |
          VERSION=$(grep '^version =' pyproject.toml | head -1 | cut -d '"' -f2)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - name: Check CHANGELOG for version
        run: |
          VERSION=${{ steps.get_version.outputs.version }}
          grep "$VERSION" CHANGELOG.md

  generate-changelog:
    needs: changelog-enforcement
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate Changelog
        run: |
          npm install -g conventional-changelog-cli
          conventional-changelog -p conventionalcommits -i CHANGELOG.md -s -r 0

  docker-and-helm-release:
    needs: generate-changelog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract version
        id: get_version
        run: |
          VERSION=$(grep '^version =' pyproject.toml | head -1 | cut -d '"' -f2)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - name: Build and push Docker image
        run: |
          VERSION=${{ steps.get_version.outputs.version }}
          docker build -t your-org/sentinel-memory-service:$VERSION .
          docker push your-org/sentinel-memory-service:$VERSION
      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.13.3
      - name: Package Helm chart
        run: helm package helm --destination packaged-helm
      - uses: actions/upload-artifact@v4
        with:
          name: helm-chart
          path: packaged-helm/*.tgz
      - name: Publish Helm chart
        uses: helm/chart-releaser-action@v1.7.0
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
